name: Claude Auto Comment

on:
  issues:
    types: [opened]

permissions:
  issues: write  # ← これを追加！

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Post a comment on the issue
        run: |
          echo "Claudeに業務改善ネタを相談中..." > comment.txt
          gh issue comment ${{ github.event.issue.number }} -F comment.txt
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
